apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    app: flask-basics
spec:
  # Enforce Pod-level security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
  containers:
    - name: web
      image: flask-basics:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
          name: http
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false  # Flask app does not need to write to root by default, but we'll keep it false to simplify.
        capabilities:
          drop:
            - ALL
