apiVersion: v1
kind: Pod
metadata:
  name: flask-config-pod
  labels:
    app: flask-config
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
  containers:
    - name: web
      image: flask-config:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
          name: http
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      env:
        # Load values from ConfigMap
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_COLOR
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
        # Load value from Secret
        - name: SECRET_MESSAGE
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SECRET_MESSAGE
