apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-deployment
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.postgres.repository }}:{{ .Values.image.postgres.tag }}"
          imagePullPolicy: {{ .Values.image.postgres.pullPolicy }}
          ports:
            - containerPort: 5432
              name: dbport
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.dbName | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.database.dbUser | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: DB_PASSWORD
            - name: PGDATA
              value: "/var/lib/postgresql/data/custom"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.database.dbUser | quote }}
                - -d
                - {{ .Values.database.dbName | quote }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.database.dbUser | quote }}
                - -d
                - {{ .Values.database.dbName | quote }}
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pvc
