apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  # Base64 encode the plain-text password from values.yaml dynamically!
  DB_PASSWORD: {{ .Values.database.dbPassword | b64enc | quote }}
  SECRET_MESSAGE: {{ "Hello from Helm-packaged Secret!" | b64enc | quote }}
